# Generated by Django 2.2.5 on 2020-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_birthday_date', models.CharField(max_length=100)),
                ('employee_birthday_year', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_birthday_month', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_age', models.IntegerField()),
                ('employee_gender', models.IntegerField()),
                ('employee_joining_date', models.DateTimeField()),
            ],
        ),
    ]
